import {DexParser} from "./dex-parser";
import {writeFileData} from "./generator-utils";

const config = {
	outputFile: "./learnset-output.ts",
};

const fileHeader = `import { ModdedLearnsetData } from "./sim/dex-species";

/*
 * DO NOT EDIT THIS FILE.
 * This file was auto-generated by {server}/tools/elite-redux/dex-parser/generate-learnsets.ts
 */
`;

async function main() {
	const parser = new DexParser();
	await parser.init();
	const fileData: string[] = [fileHeader];
	fileData.push(
		`export const Learnsets: {[k: string]: ModdedLearnsetData} = ${JSON.stringify(
			parser.learnsets,
			null,
			4
		)}`
	);
	await writeFileData(config.outputFile, fileData);
	console.debug(`Successfully wrote learnset data to ${config.outputFile}`);
}

main().then(() => process.exit(0));
