import { DexParser } from "./dex-parser";
import { writeFileData } from "./generator-utils";

const config = {
	outputFile: "./pokedex-output.ts",
};

const fileHeader = `import { ModdedSpeciesData } from "./sim/dex-species";

/*
 * DO NOT EDIT THIS FILE.
 * This file was auto-generated by {server}/tools/elite-redux/dex-parser/generate-pokedex.ts
 */
`;

async function main() {
	const parser = new DexParser();
	await parser.init();
	const fileData: string[] = [fileHeader];
	fileData.push(
		`export const Pokedex: {[k: string]: ModdedSpeciesData} = ${JSON.stringify(
			parser.pokedex,
			null,
			4
		)}`
	);
	await writeFileData(config.outputFile, fileData);
	console.debug(`Successfully wrote pokedex data to ${config.outputFile}`);
}

main().then(() => process.exit(0));
